const dummyNotifications = [
    {
        id: "notif_001",
        userId: "user_123",
        type: "like",
        title: "New Like ❤️",
        description: "Rahul liked your profile",
        relatedUserId: "user_456",
        isRead: false,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "notif_002",
        userId: "user_123",
        type: "match",
        title: "It's a Match 🎉",
        description: "You matched with Priya",
        relatedUserId: "user_789",
        isRead: false,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "notif_003",
        userId: "user_123",
        type: "message",
        title: "New Message 💬",
        description: "Aman sent you a message",
        relatedUserId: "user_321",
        isRead: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "notif_004",
        userId: "user_123",
        type: "verification",
        title: "Profile Verified ✅",
        description: "Your profile has been verified",
        relatedUserId: null,
        isRead: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "notif_005",
        userId: "user_123",
        type: "premium",
        title: "Premium Activated ⭐",
        description: "You are now a premium member",
        relatedUserId: null,
        isRead: false,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
];

export default dummyNotifications