name: Deploy to Play Store Internal Testing

on:
  # push:
  #   branches:
  #     - main  # triggers automatically when you push to main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install JS dependencies
        run: npm install

      - name: Decode Keystore
        uses: timheuer/base64-to-file@v1.2
        id: keystore_file
        with:
          fileName: 'yugma-upload-key.keystore'
          encodedString: ${{ secrets.KEYSTORE_FILE }}

      - name: Copy Keystore to App Folder
        run: mv ${{ steps.keystore_file.outputs.filePath }} android/app/yugma-upload-key.keystore

      - name: Grant execute permission to gradlew
        run: chmod +x android/gradlew

      - name: Build AAB
        run: |
          cd android
          ./gradlew bundleRelease

      - name: Upload to Play Store Internal Testing
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_JSON_KEY }}
          packageName: com.yugma.dating
          releaseFiles: android/app/build/outputs/bundle/release/app-release.aab
          tracks: internal
          status: completed